### PR TITLE
added contentinfo in video

### PR DESCRIPTION
**Pull request by anshumansworld**
This includes addition of contentinfo in feed video. In other formats it's already there.

### CODE REVIEW

**Comment by cerberillo** [comment]
@anshumansworld this patch contains changes not specified in the description or the task, let's only upload changes related.

This is the source of the conflict

**Comment by cerberillo** [comment]
[(1) Contentinfo in the video format (SDK) (Anshuman)](https://trello.com/c/dqFiDw6V/1222-1-contentinfo-in-the-video-format-sdk-anshuman)

**Comment by anshumansworld** [comment]
@cerberillo @RagnarR Can you please review it once again?

**Comment by RagnarR** [comment]
Looks good for me now

**Pull request merged**
