### PR TITLE
AdChoices icon

### PR DESCRIPTION
**Pull request by RagnarR**
Added new AdChoices icon for standard units

### CODE REVIEW

**Comment by cerberillo** [comment]
I see a problem in general with the use of the name "adchoices" when it's a registered brand and we are not using them, what we are using here is an advertising disclosure, adchoices is just a brand that groups companies following certain criteria about ad transparency and good habits.

We should change all adchoices references (even from backend) to advertisingdisclosure.

In the open behaviour, I would see good to follow the adchoices behaviour, that opens the icon when clicked in the first time.

It should basically be:

* When the user clicks the first time: Enlarges the background and shows the icon and a text `+info` right next to it.
* If the user clicks a second time when opened, it should go to the advertising disclosure
* If 5 seconds passed and the user didn't clicked again, it should automatically return to the default state.

**Comment by RagnarR** [comment]
I think you need to discuss it with Alex and Adwait.

**Comment by cerberillo** [comment]
After discussion, let's proceed with this changes @RagnarR

**Comment by RagnarR** [comment]
Let's do it at Monday :)

**Comment by cerberillo** [comment]
Change approved, let's move on to the new behaviour :)

**Comment by cerberillo** [comment]
Still missing the described `open` behaviour

**Comment by RagnarR** [comment]
No, all three points is added: Icon click open layout -> second click open url in browser / if did nothing - return to icon mode

**Comment by cerberillo** [comment]
all right lets merge theb and get it approved by qa

**Comment by cerberillo** [comment]
fixing tests before :)

**Comment by cerberillo** [comment]
👍

**Pull request merged**
