### PR TITLE
Javadoc

### PR DESCRIPTION
**Pull request by rahulrvp**
- added javadoc comments for relevant public methods in the library

### CODE REVIEW

**Comment by cerberillo** [comment]
Good work, but I would like you to go a bit deeper and comment whatever you see public before merge, please

**Comment by rahulrvp** [comment]
Sure David. I will do that.

**Comment by rahulrvp** [comment]
I have gone through all the classes and have written comments for the public methods. (some of the unused classes and constructors are skipped)

**Comment by cerberillo** [comment]
Looks pretty good, thanks for your PR

**Pull request merged**
